# **Computational Methods**
## **Class Work**
### **Numpy and Arrays**

written by Niv Keren, nivkeren1@mail.tau.ac.il 

*Computational Methods* class: 0341-2300

2020/Semester I; Tuesdays 14:00-16:00

FACULTY OF EXACT SCIENCES | GEOPHYSICS & PLANETARY SCIENCES  
Tel Aviv University

---
1. Run the first cell

In [2]:
import numpy as np

2. Create a random integers between 0 to 25, 5x5 numpy ndarray.

In [22]:
m = np.random.randint(0, 26, (5,5))
m

array([[20, 15,  5,  4,  5],
       [ 2, 11, 20, 10, 14],
       [13,  0, 14,  0, 25],
       [17,  4, 19,  1, 23],
       [24,  7, 21,  2,  8]])

2. Use `sum()` to sum the columns and and the rows in the array.

In [23]:
sum_rows = m.sum(axis=1)
sum_cols = m.sum(axis=0)
print(f'Sum rows {sum_rows}')
print(f'Sum cols {sum_cols}')

Sum rows [49 57 52 64 62]
Sum cols [76 37 79 17 75]


3. Sum all the numbers in the array

In [24]:
m.sum()

284

4. multiple the marix by 2 and add 9 to the first column 

In [25]:
m *= 2
m[:, 0] += 9
m

array([[49, 30, 10,  8, 10],
       [13, 22, 40, 20, 28],
       [35,  0, 28,  0, 50],
       [43,  8, 38,  2, 46],
       [57, 14, 42,  4, 16]])

5. Cut the 4th column of the array and save it to a new object

In [26]:
col = m[:, 3]
m = np.delete(m, 3, 1)
m

array([[49, 30, 10, 10],
       [13, 22, 40, 28],
       [35,  0, 28, 50],
       [43,  8, 38, 46],
       [57, 14, 42, 16]])

6. Find the max value of the fourth column. print the value and the index of the max value?

In [31]:
print(f'max value - {col.max()}')
print(f'max index - {col.argmax()}')

max value - 20
max index - 1


7. Find the places (indexes) of the values in the array which are bigger than 40. 

In [37]:
np.argwhere(m > 40)

array([[0, 0],
       [2, 3],
       [3, 0],
       [3, 3],
       [4, 0],
       [4, 2]])

8. Create a array with the values that are bigger than 40.

In [39]:
m40 = m[m > 40]
m40

array([49, 50, 43, 46, 57, 42])

9. replace the min value in the "bigger than twenty" array with the number 1.

In [40]:
m40[m40.argmin()] = 1
m40

array([49, 50, 43, 46, 57,  1])