# **Computational Methods**
## **COMPLEX NUMBERS**

Written by Niv Keren, nivkeren1@mail.tau.ac.il 

*Computational Methods* class: 0341-2300

2020/Semester I; Tuesdays 14:00-16:00

FACULTY OF EXACT SCIENCES | GEOPHYSICS & PLANETARY SCIENCES  
Tel Aviv University

---
Python allows a very convenient treatment of complex numbers  

Unless defined otherwise, *'i'* is the *'i'* we all know from complex
number notation - square root of -1.

In [1]:
import numpy as np

In [6]:
(-1) ** 0.5

(6.123233995736766e-17+1j)

Here you can also see the default way in which Python prints complex numbers  
This is also one way we can write complex numbers and input  
them to Python. Note the absence of any multiplication sign  
between the number and *j*.

In [11]:
c1 = 1-2j
c1

(1-2j)

Another way to construct a complex number is using the
built-in function 'complex'.

In [12]:
c1 = complex(1,-2)
c1

(1-2j)

All the arithmetic operations are defined on the  
complex numbers as we expect them to be.

In [18]:
c2 = 3 * ( 2 - 3j)
print(c2)

c3 = (-2) ** 0.5
print(c3)

c4 = (c1 + c2) / c3
print(c4)

(6-9j)
(8.659560562354934e-17+1.4142135623730951j)
(-7.7781745930520225-4.949747468305833j)


the functions `np.real()` and `np.imag()` extract the real and the imaginary part of the complex number

In [24]:
c4r = np.real(c4)

c4i = np.imag(c4)

print(c4r, c4i)

-7.7781745930520225 -4.949747468305833


For polar (Euler) representation of complex numbers we
need the absolute value and the phase.

The absolute value is obtained with the function `np.abs()`.

In [25]:
np.abs(c4)

9.219544457292887

The phase is obtained with the function `np.angle()`.
The phase is in radians betwee -pi and pi.

In [26]:
np.angle(c4)

-2.5748634360662868

The number can be easily reconstructed from the
absolute value and the phase.

In [31]:
r = np.abs(c1)
phi = np.angle(c1)

r * np.exp(phi* 1j)

(1.0000000000000002-2j)

We can also use the built-in function `np.conj()` to get the complex conjugate ('tzamud').

In [34]:
print(c1)
c1_conj = np.conj(c1)
print(c1_conj)

(1-2j)
(1+2j)


## **POLYNOMIALS**
--------------------
Python has some neat built-in functions to perform operations on polynomials.


Matlab represents a polynomial simply as 1D numpy ndarray.  
The first element hold the coefficient of the highest power, and the last holds the coefficient of the zeroth power.

This polynomial  
*x^4 - 12*x^3 + 25*x + 116*

In [36]:
p = np.array([1, -12, 0, 25, 116])
p

array([  1, -12,   0,  25, 116])

The function 'roots' assumes the vector it got as input represents a polynomial, and it returns  
a 1D Array with the roots of the polynomial.

In [39]:
np.roots(p)

array([11.74728287+0.j        ,  2.70282074+0.j        ,
       -1.22505181+1.46720801j, -1.22505181-1.46720801j])

Operations defined between polynomials

In [40]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 4, 9, 16])

Addition is very simply an element-by-element addition.

In [41]:
a + b

array([ 2,  6, 12, 20])

Multiplication is equivalent to 'convolution', so the function 'conv' is used to perform it.

In [43]:
np.convolve(a, b)

array([ 1,  6, 20, 50, 75, 84, 64])

Python can also calculate derivatives and integrals of polynomials.
**Derivative**

c = conv(a,b);
polyder(c)

%
% Integral. The additional argument is the integration constant. 
% If no constant is specified, the default is 0.
%

polyint(c)
polyint(c,28)

%
% The function 'polyval' evaluates a polynomial
% in specified locations.
%

doc polyval
polyval(c,1)
polyval(c,-4)
polyval(c,[1 5 9])

%
% For example, let's plot the polynomial 
% x^3+4*x^2-7*x-10 between x = -1 and x = 3.
%

p = [1 4 -7 -10];
x = linspace(-10,3,1000);
v = polyval(p,x);
plot (x,v)
grid

% 
% Using the plot we can test polynomial roots
%

roots(p)

%
% We can also examine where the derivative is zero
%

roots(polyder(p))

%
% Matlab also offers a way to fit a polynomial to data.
% By 'fit' we mean in the 'least squares' sense,
% i.e., the polynomial whose averaged sum of squared distances
% from the points is minimal.
%

x = 0:0.1:1;
y = [-.447 1.978 3.28 6.16 7.08 7.34 7.66 9.56 9.48 9.3 11.2];


%
% We use the function 'scatter' to get a 'scatter plot',
% where the points are not connected with lines and
% there are only markers in the form of empty circles.
% Obviously we can obtain the same plot using 'plot'
%

scatter (x,y)
plot (x,y,'o')

%
% To fit a polynomial to the data we use the function
% 'polyfit'.  Besides the input x and y data, we also have
% to specify the degree of the polynomial we wish to fit.
%

doc polyfit
polyfit(x,y,1)
polyfit(x,y,2)

%
% We'll plot the polynomial we fitted on the scatter
% plot.
%

xx = linspace(0,1,100);
hold

p1 = polyfit(x,y,1);
p2 = polyfit(x,y,2);
plot (xx,polyval(p1,xx),'k')
plot (xx,polyval(p2,xx),'r')


%
% Reminder: we started class with an explanation about
% Least-square fitting. The following website gives
% another introduction to the topic:
% http://mathworld.wolfram.com/LeastSquaresFitting.html
%